### ISSUE TITLE
Readme says TIOCSTI disabled by default for >=6.2?

### ISSUE THREAD

**Issue by hartwork** [kauruus/legacy_tiocsti#1]
Hi @kauruus,

the readme currently says:

> Since Linux Kernel 6.2, `TIOCSTI` is disabled by default.

I checked the kernel sources and https://github.com/torvalds/linux/blob/38e04b3e4240a6d8fb43129ebad41608db64bc6f/drivers/tty/Kconfig#L154 looks like its _enabled_ by default, which matches what I see in practice with 6.2.1. Is this patched by the distro that you are using? Any ideas?

Thanks and best, Sebastian

**Comment by kauruus** [comment]
yep, it's more accurate to say some Linux distribution disable it by default.

i'm using ArchLinux, it's not set:

```
$ zgrep CONFIG_LEGACY_TIOCSTI /proc/config.gz
# CONFIG_LEGACY_TIOCSTI is not set
```

**Comment by kauruus** [comment]
i have updated the readme, and will archive the repo later.

**Comment by hartwork** [comment]
Thanks for elaborating :+1:
